### ISSUE TITLE
v0.7.0-pending TODO

### ISSUE THREAD

**Issue by benhar-dev** [Mobject-Dev-Team/mobject-collections#17]
v0.7.0-pending (currently on the v0.6.1-pending branch)

TODO
- [x] add TrimExcess()
- [x] possible remove of Item for the time being
- [x] complete List documentation
- [x] finish tests (Capacity, TrimExcess)

Completed to date
- refactored names
- changed to PRIVATE AddLast by following the .Net style in favour of using Insert
- refactored AddAt to Insert
- removed AddFirst, AddFirstNode as no longer needed
- added Capacity property
- removed Initial as list will now start at 4 and double automatically.
- removed getbyindex in favour of TryGetByIndex
- removed gettobyindex in favour of TryGetToByIndex
- refactored GetNodeByIndex to Item
- refactored TryGetIndex to GetIndexOf
- added removeAllNodes to prevent memory leak
- added OnChanged and OnDisposed and linked to enumerator
- added TrimExcess in the style of .net
- added checks for capacity
